export const SET_CATEGORIES_LOADING = "SET_CATEGORIES_LOADING";
export const SET_CATEGORIES_DATA = "SET_CATEGORIES_DATA";
export const SET_CATEGORIES_ERROR = "SET_CATEGORIES_ERROR";
export const SET_ALL_CATEGORIES_PRODUCTS_LOADING =
  "SET_ALL_CATEGORIES_PRODUCTS_LOADING";
export const SET_ALL_CATEGORIES_PRODUCTS_DATA =
  "SET_ALL_CATEGORIES_PRODUCTS_DATA";
export const SET_ALL_CATEGORIES_PRODUCTS_ERROR =
  "SET_ALL_CATEGORIES_PRODUCTS_ERROR";
export const SET_SINGLE_CATEGORIES_PRODUCTS_LOADING =
  "SET_SINGLE_CATEGORIES_PRODUCTS_LOADING";
export const SET_SINGLE_CATEGORIES_PRODUCTS_DATA =
  "SET_SINGLE_CATEGORIES_PRODUCTS_DATA";
export const SET_SINGLE_CATEGORIES_PRODUCTS_ERROR =
  "SET_SINGLE_CATEGORIES_PRODUCTS_ERROR";
export const SET_SINGLE_PRODUCT_LOADING = "SET_SINGLE_PRODUCT_LOADING";
export const SET_SINGLE_PRODUCT_DATA = "SET_SINGLE_PRODUCT_DATA";
export const SET_SINGLE_PRODUCT_ERROR = "SET_SINGLE_PRODUCT_ERROR";
export const ADD_TO_CART = "ADD_TO_CART";
export const REMOVE_ITEM = "REMOVE_ITEM";
export const CLEAR_CART = "CLEAR_CART";
